- name: "Set up Bazzite"
  hosts: localhost
  connection: local
  handlers:
    - name: "Custom handlers"
      ansible.builtin.import_tasks: handlers/handlers.yaml
  tasks:
    - name: "Install repo based apps"
      ansible.builtin.include_role:
        name: overlay-apps
      tags:
        - always

    - name: "Install flatpak based apps"
      ansible.builtin.include_role:
        name: flatpak-apps
      tags:
        - always

    - name: "Install pip based apps"
      ansible.builtin.include_role:
        name: pip-apps
      tags:
        - always

    - name: "Install brew based apps"
      ansible.builtin.include_role:
        name: brew-apps
      tags:
        - always

    - name: "Set up terminal"
      ansible.builtin.include_role:
        name: terminal
      tags:
        - always

    - name: "Copy over mangohud configs"
      ansible.builtin.include_role:
        name: mangohud
      tags:
        - always

    - name: "Set up qmk"
      ansible.builtin.include_role:
        name: qmk
      tags:
        - qmk
