- name: "Brew block"
  tags: brew
  block:
    - name: "Install brew based apps"
      community.general.homebrew:
        name:
          - bat
          - eza
          - fzf
          - hadolint
          - shellcheck
          - tealdeer
          - zsh
        state: latest
        update_homebrew: true

    - name: "Install Hack font"
      community.general.homebrew_cask:
        name: font-hack
        state: latest
